COMENTARIO = 'c'
FORMATO_PROBLEMA = 'p'
INCOMPATIBILIDAD = 'e'
TIEMPO_LAVADO = 'n'

DATOS_SEP = " "
POS_TIPO_DATO = 0

POS_CANT_PRENDAS = 2
POS_CANT_INCOMPATIBILIDADES = 3

POS_PRENDA_INCOMPATIBLE_1 = 1
POS_PRENDA_INCOMPATIBLE_2 = 2

POS_PRENDA_LAVADO = 1
POS_TIEMPO_LAVADO = 2
